import type { ComparisonContent } from "../schema";
import {
  defaultGenerationMeta, defaultScores, defaultAnalytics,
  defaultLocalization, defaultAuthor, defaultRelationships,
  defaultRecommendations, defaultAIBlocks, defaultMeta,
} from "../schema";

export const markdownVsHtml: ComparisonContent = {
  id: "comparison.markdown-vs-html",
  type: "comparison",
  slug: "markdown-vs-html",
  title: "Markdown vs HTML: When to Use Each Markup Language",
  description: "Compare Markdown and HTML for content creation. Understand readability, flexibility, tooling support, and when to use each format.",
  seoTitle: "Markdown vs HTML Comparison | Markup Language Guide | ToolsAtZero",
  metaDescription: "Markdown vs HTML comparison. Learn the differences in syntax complexity, rendering, tooling, and decide which markup language fits your workflow.",
  keywords: ["markdown vs html", "markdown or html", "markup language comparison", "best markup format", "markdown advantages"],
  entityIds: ["markdown", "html", "css"],
  status: "published",
  meta: defaultMeta({ topicId: "markup.markdown-vs-html", difficulty: "beginner", readingTimeMinutes: 6, targetAudience: ["writers", "developers", "content creators", "bloggers"], searchIntents: ["comparison", "informational", "educational"], aliases: ["md vs html", "markdown versus html", "should I use markdown or html"] }),
  generation: defaultGenerationMeta(),
  scores: defaultScores(),
  analytics: defaultAnalytics({ priority: 6, expectedTraffic: "medium" }),
  localization: defaultLocalization(),
  author: defaultAuthor(),
  relationships: defaultRelationships({ siblings: ["comparison.json-vs-xml", "comparison.csv-vs-excel"], relatedCategories: ["category.developer"], relatedGuides: ["guide.json-formatter"] }),
  recommendations: defaultRecommendations({ beginner: ["guide.json-formatter"], next: ["bestof.developer-tools"] }),
  aiBlocks: defaultAIBlocks({ aiSummary: "Markdown is a lightweight syntax designed for readability and speed, ideal for documentation and content writing. HTML provides full control over structure and presentation, essential for web pages and complex layouts.", keyTakeaways: ["Markdown is simpler to write and read as plain text", "HTML offers complete control over page structure and styling", "Markdown converts to HTML for web rendering", "Use Markdown for documentation; HTML for web applications", "Most modern platforms support Markdown natively"], quickFacts: ["Markdown was created by John Gruber in 2004", "HTML was first released in 1993", "GitHub Flavored Markdown (GFM) is the most popular variant"] }),
  formatA: "Markdown",
  formatB: "HTML",
  similarities: [
    "Both are text-based markup formats",
    "Both can represent headings, lists, links, images, and code blocks",
    "Both can be version-controlled with Git",
    "Both are widely supported across development platforms",
    "Both are human-readable in their source form",
    "Both support embedded links and references",
  ],
  differences: [
    "Markdown uses minimal syntax characters; HTML uses verbose tag pairs",
    "HTML supports any layout or interactive element; Markdown is limited to common content structures",
    "Markdown is designed to be readable as plain text; raw HTML is harder to scan",
    "HTML can include CSS, JavaScript, and multimedia directly; Markdown cannot",
    "Markdown must be converted to HTML for browser rendering; HTML renders directly",
    "HTML supports semantic elements like nav, article, aside; Markdown has no semantic equivalents",
    "Markdown has multiple competing specifications (CommonMark, GFM); HTML has one W3C standard",
    "HTML supports forms, tables with merged cells, and complex layouts; Markdown supports only basic tables",
  ],
  prosA: [
    "Extremely fast to write compared to HTML",
    "Readable as plain text without rendering",
    "Ideal for documentation, READMEs, and technical writing",
    "Supported natively by GitHub, GitLab, Notion, and most developer platforms",
    "Minimal syntax reduces errors and learning curve",
  ],
  prosB: [
    "Complete control over page structure, layout, and styling",
    "Supports interactive elements, forms, and multimedia",
    "Semantic elements improve accessibility and SEO",
    "Direct browser rendering without conversion step",
    "Universal web standard with extensive tooling and documentation",
  ],
  consA: [
    "Limited formatting options for complex layouts",
    "No support for interactive elements or forms",
    "Multiple specifications create inconsistency across platforms",
    "Basic table support without cell merging or styling",
  ],
  consB: [
    "Verbose and slower to write than Markdown",
    "Harder to read as raw source text",
    "Steeper learning curve for non-developers",
    "More prone to syntax errors (unclosed tags, nesting issues)",
  ],
  performance: "Both formats are lightweight text files with negligible performance differences in file size. The conversion step from Markdown to HTML adds minimal build-time overhead. For runtime rendering, HTML is faster since it requires no parsing conversion. Static site generators pre-compile Markdown to HTML, eliminating any runtime cost.",
  compatibility: "HTML is universally supported in every browser, email client, and web platform. Markdown is natively supported by developer platforms (GitHub, GitLab, Stack Overflow), documentation tools (Docusaurus, MkDocs, Hugo), and productivity apps (Notion, Obsidian). Email clients do not support Markdown directly.",
  seoImpact: "HTML provides better SEO control through semantic elements, meta tags, structured data, and fine-grained heading hierarchy. Markdown-based sites achieve equivalent SEO when compiled through frameworks that generate proper HTML structure with metadata support.",
  bestUseCases: "Use Markdown for documentation, README files, blog posts, technical writing, notes, and any content where speed and readability matter most. Use HTML for web pages, email templates, landing pages, interactive applications, and any content requiring precise layout control.",
  recommendation: "For content-focused writing like documentation and blogs, Markdown is faster and more maintainable. For web applications and pages requiring layout control, use HTML directly. Many successful workflows combine both: write content in Markdown, build the page structure in HTML.",
  faqs: [
    { question: "What is Markdown?", answer: "Markdown is a lightweight markup language created by John Gruber in 2004, designed to be readable as plain text and convertible to HTML." },
    { question: "Can Markdown replace HTML?", answer: "Not entirely. Markdown covers common content patterns but lacks support for interactive elements, complex layouts, and semantic structure that HTML provides." },
    { question: "Is Markdown easier to learn?", answer: "Yes. Markdown syntax can be learned in minutes, while HTML requires understanding tag structure, attributes, and nesting rules." },
    { question: "How does Markdown convert to HTML?", answer: "Markdown processors like marked, remark, or pandoc parse Markdown syntax and generate equivalent HTML output." },
    { question: "Can I use HTML inside Markdown?", answer: "Most Markdown processors allow inline HTML within Markdown files, giving you the flexibility to use both syntaxes together." },
    { question: "Which format is better for blogs?", answer: "Markdown is ideal for blog content due to its readability and speed. Static site generators convert Markdown posts to HTML pages automatically." },
    { question: "Does GitHub use Markdown or HTML?", answer: "GitHub uses GitHub Flavored Markdown (GFM) for READMEs, issues, comments, and documentation, which is rendered as HTML for display." },
    { question: "Is Markdown good for SEO?", answer: "Markdown itself has no SEO features, but when compiled to HTML through frameworks that add meta tags and semantic structure, it achieves equivalent SEO." },
    { question: "What is CommonMark?", answer: "CommonMark is a strongly specified standard for Markdown syntax, created to resolve ambiguities in the original Markdown specification." },
    { question: "Can I style Markdown content?", answer: "Markdown does not support inline styling. CSS is applied to the generated HTML output, either through a framework theme or custom stylesheets." },
    { question: "Which is better for technical documentation?", answer: "Markdown is the industry standard for technical documentation due to its simplicity, version control friendliness, and wide platform support." },
    { question: "Can Markdown handle tables?", answer: "Yes, most Markdown flavors support basic tables using pipe characters, but complex tables with merged cells require HTML." },
    { question: "Is Markdown a programming language?", answer: "No. Markdown is a markup language for formatting text. It has no logic, variables, or computational capabilities." },
    { question: "What tools support Markdown?", answer: "VS Code, Obsidian, Notion, Typora, GitHub, GitLab, Hugo, Docusaurus, Jekyll, and hundreds of other tools support Markdown natively." },
  ],
  glossary: [
    { term: "Markdown", definition: "A lightweight markup language using plain text formatting syntax, designed for readability and easy conversion to HTML." },
    { term: "HTML", definition: "HyperText Markup Language — the standard markup language for creating web pages and web applications." },
    { term: "CommonMark", definition: "A strongly defined, highly compatible specification of Markdown syntax." },
    { term: "GFM", definition: "GitHub Flavored Markdown — GitHub's extended version of Markdown with tables, task lists, and strikethrough support." },
    { term: "Static Site Generator", definition: "A tool that converts source files (often Markdown) into a complete static HTML website at build time." },
    { term: "Semantic HTML", definition: "HTML elements that carry meaning about the content they contain, such as article, nav, header, and footer." },
    { term: "Markup Language", definition: "A system for annotating text to define structure and formatting, using tags or syntax distinct from the content." },
    { term: "Frontmatter", definition: "YAML or JSON metadata at the top of a Markdown file, commonly used by static site generators for page configuration." },
  ],
};
