import type { ComparisonContent } from "../schema";
import {
  defaultGenerationMeta, defaultScores, defaultAnalytics,
  defaultLocalization, defaultAuthor, defaultRelationships,
  defaultRecommendations, defaultAIBlocks, defaultMeta,
} from "../schema";

export const webpVsPng: ComparisonContent = {
  id: "comparison.webp-vs-png",
  type: "comparison",
  slug: "webp-vs-png",
  title: "WebP vs PNG: Which Image Format Is Better?",
  description: "Compare WebP and PNG image formats. Understand compression, quality, browser support, and when to use each format for web images.",
  seoTitle: "WebP vs PNG Comparison | Image Format Guide | ToolsAtZero",
  metaDescription: "WebP vs PNG detailed comparison. Learn about compression efficiency, transparency support, browser compatibility, and best use cases for each image format.",
  keywords: ["webp vs png", "webp or png", "image format comparison", "best web image format", "webp transparency"],
  entityIds: ["webp", "png", "compression-lossy", "compression-lossless"],
  status: "published",
  meta: defaultMeta({ topicId: "image.webp-vs-png", difficulty: "intermediate", readingTimeMinutes: 7, targetAudience: ["web developers", "designers", "content creators"], searchIntents: ["comparison", "informational", "performance"], aliases: ["webp or png", "webp versus png", "png vs webp for web"] }),
  generation: defaultGenerationMeta(),
  scores: defaultScores(),
  analytics: defaultAnalytics({ priority: 7, expectedTraffic: "high" }),
  localization: defaultLocalization(),
  author: defaultAuthor(),
  relationships: defaultRelationships({ siblings: ["comparison.png-vs-jpg", "comparison.json-vs-xml"], relatedCategories: ["category.image"], relatedGuides: ["guide.compress-images", "guide.convert-png-to-jpg"] }),
  recommendations: defaultRecommendations({ beginner: ["guide.compress-images"], next: ["comparison.png-vs-jpg"] }),
  aiBlocks: defaultAIBlocks({ aiSummary: "WebP delivers 25-35% smaller file sizes than PNG with equivalent quality, supporting both lossy and lossless compression plus transparency. PNG remains the safe choice for maximum compatibility and lossless quality.", keyTakeaways: ["WebP files are 25-35% smaller than equivalent PNG files", "Both formats support transparency (alpha channels)", "WebP supports both lossy and lossless compression", "PNG has universal browser support; WebP is supported in all modern browsers", "Use WebP for web performance; use PNG when maximum compatibility is required"], quickFacts: ["WebP was developed by Google in 2010", "PNG was standardized in 1996", "WebP supports animation (alternative to GIF)"] }),
  formatA: "WebP",
  formatB: "PNG",
  similarities: [
    "Both support alpha channel transparency",
    "Both support lossless compression",
    "Both are raster image formats",
    "Both support embedded color profiles",
    "Both are patent-free and open formats",
    "Both are widely used for web graphics",
  ],
  differences: [
    "WebP supports both lossy and lossless compression; PNG is lossless only",
    "WebP files are 25-35% smaller than equivalent PNG files",
    "WebP supports animation; PNG requires APNG extension for animation",
    "PNG has universal support in all browsers and tools; WebP lacks support in some older software",
    "WebP encoding is more CPU-intensive than PNG encoding",
    "PNG supports higher bit depths (up to 48-bit color); WebP is limited to 32-bit",
    "WebP uses predictive coding for better compression; PNG uses DEFLATE",
    "PNG is better supported in print workflows; WebP is web-focused",
  ],
  prosA: [
    "25-35% smaller file sizes compared to PNG at equivalent quality",
    "Supports both lossy and lossless compression modes",
    "Built-in animation support (replacement for GIF)",
    "Excellent transparency support with smaller file sizes",
    "Recommended by Google for Core Web Vitals optimization",
  ],
  prosB: [
    "Universal browser and software compatibility",
    "Guaranteed lossless quality preservation",
    "Higher bit depth support for professional graphics",
    "Widely supported in print and design workflows",
    "Simple and well-understood compression algorithm",
  ],
  consA: [
    "Not supported in some older browsers and image editors",
    "Higher encoding CPU cost compared to PNG",
    "Limited adoption in print and professional design tools",
    "Maximum image dimensions are 16383×16383 pixels",
  ],
  consB: [
    "Significantly larger file sizes than WebP",
    "No built-in lossy compression option",
    "Animation support requires APNG which has limited adoption",
    "Slower page load times due to larger file sizes",
  ],
  performance: "WebP delivers consistently smaller files: lossless WebP is 26% smaller than PNG on average according to Google benchmarks. For photographs with transparency, lossy WebP can reduce file sizes by up to 60% compared to 24-bit PNG with alpha channels. WebP encoding takes slightly longer but decoding speed is comparable.",
  compatibility: "WebP is supported in Chrome, Firefox, Edge, Safari (14+), and all modern mobile browsers, covering over 97% of global browser usage. PNG has truly universal support in every browser, image editor, and operating system ever built. For email and legacy systems, PNG remains safer.",
  seoImpact: "Google explicitly recommends WebP for web performance optimization. Using WebP improves Core Web Vitals scores (specifically Largest Contentful Paint), which directly influences search rankings. Smaller images also reduce bandwidth costs and improve mobile experience.",
  bestUseCases: "Use WebP for web publishing where performance matters: hero images, product photos, thumbnails, and any images served to modern browsers. Use PNG for design assets, screenshots requiring pixel-perfect accuracy, images in email templates, and content targeting legacy systems.",
  recommendation: "For modern web projects, WebP is the superior choice due to smaller file sizes and broad browser support. Serve WebP with PNG fallback using the HTML picture element for maximum compatibility. Use PNG directly when targeting legacy systems, email clients, or professional print workflows.",
  faqs: [
    { question: "Is WebP better than PNG?", answer: "For web use, yes. WebP produces 25-35% smaller files with equivalent visual quality while supporting both lossy and lossless compression." },
    { question: "Does WebP support transparency?", answer: "Yes. WebP supports full alpha channel transparency in both lossy and lossless modes, with smaller file sizes than PNG transparency." },
    { question: "Can all browsers display WebP?", answer: "All modern browsers support WebP, covering over 97% of global users. Only very old browser versions lack support." },
    { question: "Should I convert all PNGs to WebP?", answer: "For web delivery, converting to WebP improves performance. Keep original PNGs for editing and archival purposes." },
    { question: "Does WebP reduce image quality?", answer: "Lossless WebP preserves exact quality like PNG. Lossy WebP reduces quality slightly for much smaller files, similar to JPEG compression." },
    { question: "Is WebP good for screenshots?", answer: "Yes. Lossless WebP handles screenshots well with smaller file sizes than PNG, though sharp text edges may benefit from PNG's simpler compression." },
    { question: "Can I use WebP in email?", answer: "No. Most email clients do not support WebP. Use PNG or JPEG for email images." },
    { question: "Does Google prefer WebP for SEO?", answer: "Google recommends next-gen formats like WebP for better Core Web Vitals scores, which can positively influence search rankings." },
    { question: "How do I serve WebP with PNG fallback?", answer: "Use the HTML picture element with a WebP source and PNG fallback. Browsers automatically select the best supported format." },
    { question: "Is PNG going to be replaced by WebP?", answer: "PNG remains essential for compatibility and professional workflows. WebP complements PNG for web delivery but does not replace it entirely." },
    { question: "Can I animate WebP images?", answer: "Yes. WebP supports animation natively, making it a modern alternative to GIF with better compression and color support." },
    { question: "What tools convert PNG to WebP?", answer: "Browser-based converters like ToolsAtZero, command-line tools like cwebp, and image editors like GIMP all support PNG to WebP conversion." },
    { question: "Is WebP open source?", answer: "Yes. WebP is developed by Google and released under a BSD-style license. The format specification and reference implementation are open." },
    { question: "Does WebP support high bit depth?", answer: "WebP supports up to 32-bit color (8 bits per channel plus alpha). For higher bit depths, PNG supports up to 48-bit color." },
    { question: "Which format loads faster on mobile?", answer: "WebP loads faster on mobile due to significantly smaller file sizes, reducing download time and data usage." },
  ],
  glossary: [
    { term: "WebP", definition: "An image format developed by Google that supports both lossy and lossless compression with transparency and animation." },
    { term: "PNG", definition: "Portable Network Graphics — a lossless raster image format with transparency support, widely used on the web." },
    { term: "Alpha Channel", definition: "A component of an image that defines transparency levels for each pixel." },
    { term: "Lossless Compression", definition: "Compression that reduces file size without any loss of data or visual quality." },
    { term: "Lossy Compression", definition: "Compression that reduces file size by discarding some data, resulting in slight quality reduction." },
    { term: "DEFLATE", definition: "The compression algorithm used by PNG, combining LZ77 and Huffman coding." },
    { term: "Core Web Vitals", definition: "Google's set of metrics measuring real-world user experience including loading, interactivity, and visual stability." },
    { term: "APNG", definition: "Animated PNG — an extension of PNG that supports animation, with limited browser adoption." },
    { term: "Predictive Coding", definition: "A compression technique used by WebP that predicts pixel values based on neighboring pixels." },
    { term: "Raster Image", definition: "An image composed of a grid of pixels, as opposed to vector images which use mathematical paths." },
  ],
};
