import {
  FileText,
  Files,
  Scissors,
  FileDown,
  Image as ImageIcon,
  Lock,
  Unlock,
  FileImage,
  FileUp,
  Bookmark,
  ListOrdered,
  Droplets,
  Stamp,
  EyeOff,
  FileInput,
  FileMinus,
  Layers,
  PenTool,
  Pilcrow,
  Contrast,
  Palette,
  Type,
  FileCog,
  Info,
  Archive,
  Wrench,
  Gauge,
  Ruler,
  Unlink,
  ShieldCheck,
  Brush,
  SearchX,
  FileKey,
  ScanText,
  Shuffle,
  Paperclip,
  Download,
  ImageDown,
  FileEdit,
  TableColumnsSplit,
  FilePlus2,
  ArrowDownZA,
  RefreshCw,
  RotateCw,
  Layers2,
  Tag,
  Clock,
  LayoutGrid,
  LayoutDashboard,
  UnfoldVertical,
  StretchHorizontal,
  GitCompare,
  NotepadTextDashed,
  RulerDimensionLine,
  BrushCleaning,
  LockKeyhole,
  BookOpen,
  Smartphone,
  Grid2x2,
  FileType,
  Mail,
  BookImage,
  Archive as ArchiveIcon,
  Type as TypeIcon,
  Table,
  Layers as LayersIcon,
  ShieldAlert,
  BookMarked,
  RefreshCcw,
  Brush as BrushIcon,
  Unlink as UnlinkIcon,
  ListOrdered as ListOrderedIcon,
  FileSpreadsheet,
  AlignHorizontalDistributeCenter,
  Columns2,
  Expand,
  Pencil,
  CheckSquare,
  Crop,
  NotepadText,
  LayoutGrid as LayoutGridIcon,
  FileX,
  Link2,
  type LucideIcon,
} from "lucide-react";
import type { Tool } from "./tools";
import type { PdfToolOp, PdfToolOptions } from "./pdf/pdf-engine";

export interface PdfToolConfig {
  op: PdfToolOp;
  accept: string[];
  maxFiles: number;
  /** extra options baked in (e.g. image format) */
  fixed?: Partial<PdfToolOptions>;
  /** which option controls to show in the UI */
  controls?: Array<"pages" | "ranges" | "angle" | "quality" | "format" | "dpi" | "text" | "password" | "ownerPassword" | "title" | "author" | "subject" | "keywords" | "startNumber" | "removeMetadata">;
}

const ICON: LucideIcon = FileText;

// Slugs that already exist as dedicated ToolsAtZero pages — skip to avoid duplicates.
const EXCLUDE = new Set<string>([
  "edit-pdf",
  "crop-pdf",
  "merge-pdf",
  "split-pdf",
  "compress-pdf",
  "image-to-pdf",
  "png-to-pdf",
  "word-to-pdf",
  "excel-to-pdf",
  "powerpoint-to-pdf",
  "protect-pdf",
  "unlock-pdf",
  "pdf-to-image",
  "add-pdf-page-numbers",
  "add-watermark-to-pdf",
  "edit-pdf-metadata",
  "pdf-extract-pages",
  "remove-pdf-pages",
]);

const PDF = [".pdf"];
const IMAGES = [".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff", ".svg", ".heic"];

interface Entry {
  op: PdfToolOp;
  icon: LucideIcon;
  name: string;
  maxFiles?: number;
  accept?: string[];
  fixed?: Partial<PdfToolOptions>;
  controls?: PdfToolConfig["controls"];
}

const RAW: Record<string, Entry> = {
  "pdf-multi-tool": { op: "merge", icon: PenTool, name: "PDF Multi-Tool" },
  "jpg-to-pdf": { op: "image-to-pdf", icon: ImageIcon, name: "JPG to PDF", accept: [".jpg", ".jpeg"] },
  "sign-pdf": { op: "coming-soon", icon: PenTool, name: "Sign PDF" },
  "extract-pages": { op: "extract", icon: Files, name: "Extract Pages", controls: ["pages"] },
  "organize-pdf": { op: "coming-soon", icon: Files, name: "Organize PDF" },
  "delete-pages": { op: "remove", icon: FileMinus, name: "Delete Pages", controls: ["pages"] },
  "bookmark": { op: "coming-soon", icon: Bookmark, name: "Bookmark" },
  "table-of-contents": { op: "coming-soon", icon: ListOrdered, name: "Table of Contents" },
  "page-numbers": { op: "page-numbers", icon: ListOrdered, name: "Page Numbers", controls: ["startNumber"] },
  "add-watermark": { op: "watermark", icon: Droplets, name: "Add Watermark", controls: ["text"] },
  "header-footer": { op: "coming-soon", icon: Pilcrow, name: "Header & Footer" },
  "invert-colors": { op: "coming-soon", icon: Contrast, name: "Invert Colors" },
  "background-color": { op: "coming-soon", icon: Palette, name: "Background Color" },
  "text-color": { op: "coming-soon", icon: Type, name: "Text Color" },
  "add-stamps": { op: "watermark", icon: Stamp, name: "Add Stamps", controls: ["text"] },
  "remove-annotations": { op: "coming-soon", icon: EyeOff, name: "Remove Annotations" },
  "form-filler": { op: "coming-soon", icon: FileInput, name: "Form Filler" },
  "form-creator": { op: "coming-soon", icon: FileInput, name: "Form Creator" },
  "remove-blank-pages": { op: "coming-soon", icon: FileMinus, name: "Remove Blank Pages" },
  "webp-to-pdf": { op: "image-to-pdf", icon: ImageIcon, name: "WebP to PDF", accept: [".webp"] },
  "svg-to-pdf": { op: "image-to-pdf", icon: ImageIcon, name: "SVG to PDF", accept: [".svg"] },
  "bmp-to-pdf": { op: "image-to-pdf", icon: ImageIcon, name: "BMP to PDF", accept: [".bmp"] },
  "heic-to-pdf": { op: "image-to-pdf", icon: ImageIcon, name: "HEIC to PDF", accept: [".heic", ".heif"] },
  "tiff-to-pdf": { op: "image-to-pdf", icon: ImageIcon, name: "TIFF to PDF", accept: [".tiff", ".tif"] },
  "txt-to-pdf": { op: "coming-soon", icon: FileText, name: "TXT to PDF", accept: [".txt"] },
  "json-to-pdf": { op: "coming-soon", icon: FileText, name: "JSON to PDF", accept: [".json"] },
  "psd-to-pdf": { op: "coming-soon", icon: ImageIcon, name: "PSD to PDF", accept: [".psd", ".psb"] },
  "xps-to-pdf": { op: "coming-soon", icon: FileText, name: "XPS to PDF", accept: [".xps"] },
  "rtf-to-pdf": { op: "coming-soon", icon: FileType, name: "RTF to PDF", accept: [".rtf"] },
  "epub-to-pdf": { op: "coming-soon", icon: BookOpen, name: "EPUB to PDF", accept: [".epub"] },
  "mobi-to-pdf": { op: "coming-soon", icon: BookOpen, name: "MOBI to PDF", accept: [".mobi", ".azw", ".azw3"] },
  "djvu-to-pdf": { op: "coming-soon", icon: FileImage, name: "DJVU to PDF", accept: [".djvu", ".djv"] },
  "fb2-to-pdf": { op: "coming-soon", icon: BookOpen, name: "FB2 to PDF", accept: [".fb2", ".fb2.zip"] },
  "pdf-to-jpg": { op: "pdf-to-image", icon: FileImage, name: "PDF to JPG", fixed: { format: "jpg" }, controls: ["dpi"] },
  "pdf-to-png": { op: "pdf-to-image", icon: FileImage, name: "PDF to PNG", fixed: { format: "png" }, controls: ["dpi"] },
  "pdf-to-webp": { op: "pdf-to-image", icon: FileImage, name: "PDF to WebP", fixed: { format: "webp" }, controls: ["dpi"] },
  "pdf-to-bmp": { op: "pdf-to-image", icon: FileImage, name: "PDF to BMP", fixed: { format: "bmp" }, controls: ["dpi"] },
  "pdf-to-tiff": { op: "pdf-to-image", icon: FileImage, name: "PDF to TIFF", fixed: { format: "tiff" }, controls: ["dpi"] },
  "pdf-to-cbz": { op: "coming-soon", icon: BookImage, name: "PDF to CBZ" },
  "pdf-to-svg": { op: "coming-soon", icon: FileText, name: "PDF to SVG" },
  "pdf-to-greyscale": { op: "greyscale", icon: Contrast, name: "PDF to Greyscale" },
  "pdf-to-json": { op: "extract-text", icon: FileText, name: "PDF to JSON", fixed: { format: "json" } },
  "pdf-to-docx": { op: "coming-soon", icon: FileText, name: "PDF to DOCX" },
  "pdf-to-pptx": { op: "coming-soon", icon: FileText, name: "PDF to PPTX" },
  "pptx-to-pdf": { op: "coming-soon", icon: FileText, name: "PPTX to PDF", accept: [".pptx", ".ppt"] },
  "pdf-to-excel": { op: "coming-soon", icon: FileSpreadsheet, name: "PDF to Excel" },
  "pdf-to-markdown": { op: "extract-text", icon: FileText, name: "PDF to Markdown", fixed: { format: "md" } },
  "ocr-pdf": { op: "coming-soon", icon: ScanText, name: "OCR PDF" },
  "alternate-merge": { op: "merge", icon: Shuffle, name: "Alternate Merge" },
  "add-attachments": { op: "coming-soon", icon: Paperclip, name: "Add Attachments" },
  "extract-attachments": { op: "coming-soon", icon: Download, name: "Extract Attachments" },
  "extract-images": { op: "coming-soon", icon: ImageDown, name: "Extract Images" },
  "edit-attachments": { op: "coming-soon", icon: FileEdit, name: "Edit Attachments" },
  "divide-pages": { op: "coming-soon", icon: TableColumnsSplit, name: "Divide Pages" },
  "add-blank-page": { op: "coming-soon", icon: FilePlus2, name: "Add Blank Page" },
  "reverse-pages": { op: "reverse", icon: ArrowDownZA, name: "Reverse Pages" },
  "rotate-custom": { op: "rotate", icon: RefreshCw, name: "Rotate Custom", controls: ["angle", "pages"] },
  "rotate-pdf": { op: "rotate", icon: RotateCw, name: "Rotate PDF", fixed: { angle: 90 }, controls: ["pages"] },
  "overlay-pdf": { op: "coming-soon", icon: Layers, name: "Overlay PDF" },
  "add-page-labels": { op: "page-numbers", icon: Tag, name: "Add Page Labels", controls: ["startNumber"] },
  "timestamp-pdf": { op: "coming-soon", icon: Clock, name: "Timestamp PDF" },
  "n-up-pdf": { op: "coming-soon", icon: LayoutGrid, name: "N-Up PDF" },
  "grid-combine": { op: "merge", icon: LayoutDashboard, name: "Grid Combine" },
  "combine-single-page": { op: "coming-soon", icon: UnfoldVertical, name: "Combine Single Page" },
  "view-metadata": { op: "coming-soon", icon: Info, name: "View Metadata" },
  "edit-metadata": { op: "metadata", icon: FileCog, name: "Edit Metadata", controls: ["title", "author", "subject", "keywords"] },
  "pdf-to-zip": { op: "coming-soon", icon: ArchiveIcon, name: "PDF to ZIP" },
  "compare-pdfs": { op: "coming-soon", icon: GitCompare, name: "Compare PDFs" },
  "posterize-pdf": { op: "coming-soon", icon: NotepadTextDashed, name: "Posterize PDF" },
  "fix-page-size": { op: "coming-soon", icon: RulerDimensionLine, name: "Fix Page Size" },
  "linearize-pdf": { op: "compress", icon: Gauge, name: "Linearize PDF", fixed: { quality: "maximum" } },
  "page-dimensions": { op: "coming-soon", icon: Ruler, name: "Page Dimensions" },
  "remove-restrictions": { op: "decrypt", icon: Unlink, name: "Remove Restrictions", controls: ["password"] },
  "repair-pdf": { op: "coming-soon", icon: Wrench, name: "Repair PDF" },
  "encrypt-pdf": { op: "encrypt", icon: Lock, name: "Encrypt PDF", controls: ["password", "ownerPassword"] },
  "sanitize-pdf": { op: "remove-metadata", icon: BrushCleaning, name: "Sanitize PDF" },
  "find-and-redact": { op: "coming-soon", icon: SearchX, name: "Find & Redact" },
  "decrypt-pdf": { op: "decrypt", icon: Unlock, name: "Decrypt PDF", controls: ["password"] },
  "flatten-pdf": { op: "coming-soon", icon: Layers, name: "Flatten PDF" },
  "remove-metadata": { op: "remove-metadata", icon: FileX, name: "Remove Metadata" },
  "change-permissions": { op: "coming-soon", icon: ShieldCheck, name: "Change Permissions" },
  "digital-sign-pdf": { op: "coming-soon", icon: FileKey, name: "Digital Sign PDF" },
  "validate-signature": { op: "coming-soon", icon: ShieldCheck, name: "Validate Signature" },
  "deskew-pdf": { op: "coming-soon", icon: ScanText, name: "Deskew PDF" },
  "pdf-booklet": { op: "coming-soon", icon: BookOpen, name: "PDF Booklet" },
  "rasterize-pdf": { op: "pdf-to-image", icon: Grid2x2, name: "Rasterize PDF", controls: ["format", "dpi"] },
  "markdown-to-pdf": { op: "coming-soon", icon: FileType, name: "Markdown to PDF", accept: [".md", ".markdown"] },
  "email-to-pdf": { op: "coming-soon", icon: Mail, name: "Email to PDF", accept: [".eml", ".msg"] },
  "cbz-to-pdf": { op: "image-to-pdf", icon: BookImage, name: "CBZ to PDF", accept: [".cbz", ".zip"] },
  "pdf-to-pdfa": { op: "coming-soon", icon: ArchiveIcon, name: "PDF to PDF/A" },
  "font-to-outline": { op: "coming-soon", icon: TypeIcon, name: "Font to Outline" },
  "extract-tables": { op: "coming-soon", icon: Table, name: "Extract Tables" },
  "ocg-manager": { op: "coming-soon", icon: LayersIcon, name: "OCG Manager" },
  "pdf-reader": { op: "coming-soon", icon: BookOpen, name: "PDF Reader" },
  "ai-pdf-reflower": { op: "coming-soon", icon: Smartphone, name: "AI PDF Reflower" },
  "citation-linker": { op: "coming-soon", icon: Link2, name: "Citation Linker" },
  "vector-extractor": { op: "coming-soon", icon: LayersIcon, name: "Vector Extractor" },
  "deep-sanitize": { op: "remove-metadata", icon: ShieldAlert, name: "Deep Sanitize" },
  "booklet-folding-simulator": { op: "coming-soon", icon: BookOpen, name: "Booklet Folding Simulator" },
  "pdf-to-slide": { op: "coming-soon", icon: FileText, name: "PDF to Slide" },
  "form-logic-designer": { op: "coming-soon", icon: FileInput, name: "Form Logic Designer" },
  "eink-optimizer": { op: "greyscale", icon: Contrast, name: "E-ink Optimizer" },
  "cert-cryptor": { op: "encrypt", icon: LockKeyhole, name: "Cert Cryptor", controls: ["password"] },
  "passport-id-composer": { op: "image-to-pdf", icon: ImageIcon, name: "Passport ID Composer", accept: [".pdf", ".jpg", ".jpeg", ".png"], maxFiles: 2 },
  "annotation-exporter": { op: "coming-soon", icon: BookOpen, name: "Annotation Exporter" },
  "batch-watermark-remover": { op: "coming-soon", icon: BrushIcon, name: "Batch Watermark Remover" },
  "smart-data-redactor": { op: "coming-soon", icon: ShieldCheck, name: "Smart Data Redactor" },
  "bookmarks-auto-generator": { op: "coming-soon", icon: BookMarked, name: "Bookmarks Auto Generator" },
  "batch-barcode-injector": { op: "watermark", icon: RefreshCcw, name: "Batch Barcode Injector", controls: ["text"] },
  "signature-ink-optimizer": { op: "coming-soon", icon: BrushIcon, name: "Signature Ink Optimizer", accept: [".jpg", ".jpeg", ".png"] },
  "dead-link-debugger": { op: "coming-soon", icon: UnlinkIcon, name: "Dead Link Debugger" },
  "interactive-toc-generator": { op: "coming-soon", icon: ListOrderedIcon, name: "Interactive TOC Generator" },
  "global-invoice-parser": { op: "coming-soon", icon: FileSpreadsheet, name: "Global Invoice Parser" },
  "pdf-deskew-aligner": { op: "coming-soon", icon: AlignHorizontalDistributeCenter, name: "PDF Deskew Aligner" },
  "pdf-two-column-reflower": { op: "coming-soon", icon: Columns2, name: "PDF Two Column Reflower" },
  "pdf-page-resizer-uniform": { op: "coming-soon", icon: Expand, name: "PDF Page Resizer Uniform" },
  "handwriting-ink-contrast-booster": { op: "coming-soon", icon: Pencil, name: "Handwriting Ink Contrast Booster" },
  "pdf-spine-bookbinder": { op: "coming-soon", icon: BookOpen, name: "PDF Spine Bookbinder" },
  "pdf-signature-anchor-helper": { op: "coming-soon", icon: CheckSquare, name: "PDF Signature Anchor Helper" },
  "pdf-lossless-slicer": { op: "coming-soon", icon: Crop, name: "PDF Lossless Slicer" },
  "pdf-scratchpad-canvas": { op: "coming-soon", icon: NotepadText, name: "PDF Scratchpad Canvas" },
  "photo-tiling-prepress": { op: "image-to-pdf", icon: LayoutGridIcon, name: "Photo Tiling Prepress", accept: [".jpg", ".jpeg", ".png"], maxFiles: 20 },
};

function titleCase(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export const pdfToolConfig: Record<string, PdfToolConfig> = {};
export const pdfCraftTools: Tool[] = Object.entries(RAW)
  .filter(([slug]) => !EXCLUDE.has(slug))
  .map(([slug, e]) => {
    const op = e.op;
    const isReady = op !== "coming-soon";
    const accept = e.accept || (op === "image-to-pdf" ? IMAGES : PDF);
    const maxFiles = e.maxFiles ?? (op === "merge" || op === "image-to-pdf" ? 100 : 1);
    pdfToolConfig[slug] = {
      op,
      accept,
      maxFiles,
      fixed: e.fixed,
      controls: e.controls,
    };
    return {
      slug,
      name: e.name,
      shortName: e.name,
      description: `${e.name} — process your PDF entirely client-side with PyMuPDF. No uploads, 100% private.`,
      tagline: `${e.name} in your browser`,
      keywords: [slug, e.name.toLowerCase(), "pdf", "client-side", "private"],
      icon: e.icon || ICON,
      href: `/tools/${slug}`,
      isReady,
      category: "pdf" as const,
      targetSeoString: `Free ${e.name} Online | 100% Private | ToolsAtZero`,
    } satisfies Tool;
  });
