import { Brain, Camera, Sparkles } from "lucide-react";
import {
  Braces,
  GitCompareArrows,
  Hash,
  Database,
  Code,
  Search,
  FileCode,
  Clock,
  Fingerprint,
  Terminal,
  FileImage,
  Maximize2,
  Image,
  Crop,
  Pipette,
  RefreshCw,
  Sliders,
  EyeOff,
  Sun,
  Link2,
  Globe,
  Trash2,
  Tags,
  Bot,
  Map,
  Server,
  Calendar,
  Timer,
  Play,
  CalendarDays,
  CalendarRange,
  CalendarPlus,
  HelpCircle,
  FileSpreadsheet,
  LetterText,
  FileCode2,
  CaseSensitive,
  Volume2,
  ChevronsUpDown,
  AlignLeft,
  ListOrdered,
  Binary,
  KeyRound,
  Lock,
  Unlock,
  FileDown,
  Files,
  Scissors,
  FileText,
  FileMinus,
  FileUp,
  Settings,
  Pen,
  type LucideIcon,
} from "lucide-react";

export interface Tool {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  tagline: string;
  keywords: string[];
  icon: LucideIcon;
  href: string;
  isReady: boolean;
  category: "pdf" | "developer" | "office" | "image" | "web" | "time" | "calculator";
  targetSeoString: string;
}

const initialTools: Tool[] = [
  // ── 1. PDF SUITE (16 Tools) ──
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    targetSeoString: "Free Protect PDF Online | 100% Private | ToolsAtZero",
    shortName: "Protect PDF",
    description: "Encrypt and password-protect your PDF files 100% client-side.",
    tagline: "Encrypt and password-protect your PDF files",
    keywords: ["protect pdf", "password pdf", "encrypt pdf", "pdf security", "client-side"],
    icon: Lock,
    href: "/tools/protect-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    targetSeoString: "Free Unlock PDF Online | 100% Private | ToolsAtZero",
    shortName: "Unlock PDF",
    description: "Remove passwords and restriction blocks from PDF documents instantly.",
    tagline: "Remove password and restriction blocks from PDF",
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf", "pdf unlocker", "client-side"],
    icon: Unlock,
    href: "/tools/unlock-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    targetSeoString: "Free Compress PDF Online | 100% Private | ToolsAtZero",
    shortName: "Compress PDF",
    description: "Reduce the file size of PDF documents while maintaining visual resolution.",
    tagline: "Reduce the size of your PDF files",
    keywords: ["compress pdf", "shrink pdf", "reduce pdf size", "pdf optimizer", "client-side"],
    icon: FileDown,
    href: "/tools/compress-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    targetSeoString: "Free Crop PDF Online | 100% Private | ToolsAtZero",
    shortName: "Crop PDF",
    description: "Crop margins and adjust boundary coordinate boxes on PDF pages.",
    tagline: "Crop margins and adjust PDF layouts",
    keywords: ["crop pdf", "cut pdf pages", "pdf cropper", "adjust pdf boundaries", "client-side"],
    icon: Crop,
    href: "/tools/crop-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    targetSeoString: "Free Merge PDF Online | 100% Private | ToolsAtZero",
    shortName: "Merge PDF",
    description: "Combine multiple PDF documents into a single organized file.",
    tagline: "Combine multiple PDF files into one",
    keywords: ["merge pdf", "combine pdfs", "join pdf", "pdf merger", "client-side"],
    icon: Files,
    href: "/tools/merge-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    targetSeoString: "Free Split PDF Online | 100% Private | ToolsAtZero",
    shortName: "Split PDF",
    description: "Divide PDF documents into separate pages or custom range files.",
    tagline: "Extract pages and split PDF files",
    keywords: ["split pdf", "extract pdf pages", "separate pdf", "pdf splitter", "client-side"],
    icon: Scissors,
    href: "/tools/split-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "add-pdf-page-numbers",
    name: "Add Page Numbers",
    targetSeoString: "Free Add Page Numbers Online | 100% Private | ToolsAtZero",
    shortName: "Page Numbers",
    description: "Number PDF pages sequentially with custom positions and fonts.",
    tagline: "Add sequential page numbers to PDFs",
    keywords: ["pdf page numbers", "number pdf", "paginate pdf", "page numberer", "client-side"],
    icon: Hash,
    href: "/tools/add-pdf-page-numbers",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "add-watermark-to-pdf",
    name: "Add Watermark",
    targetSeoString: "Free Add Watermark Online | 100% Private | ToolsAtZero",
    shortName: "Watermark",
    description: "Add text stamp watermarks over your PDF sheets for copyright protection.",
    tagline: "Stamp custom text watermarks onto PDFs",
    keywords: ["watermark pdf", "pdf watermark", "stamp pdf", "copyright pdf", "client-side"],
    icon: FileText,
    href: "/tools/add-watermark-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "remove-pdf-pages",
    name: "Remove PDF Pages",
    targetSeoString: "Free Remove PDF Pages Online | 100% Private | ToolsAtZero",
    shortName: "Remove Pages",
    description: "Delete unnecessary pages from a PDF document locally.",
    tagline: "Delete select pages from a PDF document",
    keywords: ["remove pdf pages", "delete pdf pages", "clean pdf", "pdf page editor", "client-side"],
    icon: FileMinus,
    href: "/tools/remove-pdf-pages",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "pdf-extract-pages",
    name: "Extract Specific Pages",
    targetSeoString: "Free Extract Specific Pages Online | 100% Private | ToolsAtZero",
    shortName: "Extract Pages",
    description: "Isolate and save specific pages from your PDF file.",
    tagline: "Extract specific page indexes from a PDF",
    keywords: ["extract pdf pages", "pdf page extractor", "save pdf pages", "client-side"],
    icon: Files,
    href: "/tools/pdf-extract-pages",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "pdf-to-image",
    name: "PDF to Image",
    targetSeoString: "Free PDF to Image Online | 100% Private | ToolsAtZero",
    shortName: "PDF to Image",
    description: "Convert PDF sheets to PNG/JPG image files client-side.",
    tagline: "Render PDF document pages to images",
    keywords: ["pdf to image", "pdf to png", "pdf to jpg", "pdf render", "client-side"],
    icon: FileImage,
    href: "/tools/pdf-to-image",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    targetSeoString: "Free Image to PDF Online | 100% Private | ToolsAtZero",
    shortName: "Image to PDF",
    description: "Compile PNG, JPG, and webp images into a clean PDF document.",
    tagline: "Compile multiple images into a PDF file",
    keywords: ["image to pdf", "convert images to pdf", "png to pdf", "jpg to pdf", "client-side"],
    icon: FileUp,
    href: "/tools/image-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    targetSeoString: "Free Excel to PDF Online | 100% Private | ToolsAtZero",
    shortName: "Excel to PDF",
    description: "Format and export spreadsheet files (.xlsx/.csv) to PDF document layouts.",
    tagline: "Convert spreadsheets to PDF documents",
    keywords: ["excel to pdf", "xlsx to pdf", "csv to pdf", "spreadsheet export", "client-side"],
    icon: FileSpreadsheet,
    href: "/tools/excel-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    targetSeoString: "Free Word to PDF Online | 100% Private | ToolsAtZero",
    shortName: "Word to PDF",
    description: "Convert standard Word documents (.docx) to high-fidelity PDF pages.",
    tagline: "Convert Word documents to PDF layouts",
    keywords: ["word to pdf", "docx to pdf", "convert docx", "document conversion", "client-side"],
    icon: FileText,
    href: "/tools/word-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    targetSeoString: "Free PowerPoint to PDF Online | 100% Private | ToolsAtZero",
    shortName: "PPT to PDF",
    description: "Convert slide presentation formats (.pptx) to standard PDF pages.",
    tagline: "Convert slide presentations to PDF books",
    keywords: ["ppt to pdf", "powerpoint to pdf", "pptx to pdf", "slides converter", "client-side"],
    icon: FileText,
    href: "/tools/powerpoint-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "edit-pdf",
    name: "Edit PDF",
    targetSeoString: "Free Edit PDF Online | 100% Private | ToolsAtZero",
    shortName: "Edit PDF",
    description: "Add text, shapes, highlights, and sticky notes to your PDF documents.",
    tagline: "Annotate and edit PDF files in the browser",
    keywords: ["edit pdf", "pdf editor", "annotate pdf", "add text to pdf", "pdf annotation", "client-side"],
    icon: Pen,
    href: "/tools/edit-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "edit-pdf-metadata",
    name: "Edit Metadata",
    targetSeoString: "Free Edit Metadata Online | 100% Private | ToolsAtZero",
    shortName: "PDF Metadata",
    description: "Edit PDF properties like author, title, keywords, and creation dates.",
    tagline: "Update properties and metadata of a PDF",
    keywords: ["edit pdf metadata", "pdf properties", "change pdf author", "pdf keywords", "client-side"],
    icon: Settings,
    href: "/tools/edit-pdf-metadata",
    isReady: true,
    category: "pdf",
  },

  // ── 2. DEVELOPER TOOLS (10 Tools) ──
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    targetSeoString: "Free JSON Formatter & Validator Online | 100% Private | ToolsAtZero",
    shortName: "JSON Formatter",
    description: "Beautify, validate, and minify JSON structures locally.",
    tagline: "Format, validate, and minify JSON data",
    keywords: ["json formatter", "validate json", "beautify json", "json validator", "client-side"],
    icon: Braces,
    href: "/tools/json-formatter",
    isReady: true,
    category: "developer",
  },
  {
    slug: "base64-encoder-decoder",
    name: "Base64 Encoder/Decoder",
    targetSeoString: "Free Base64 Encoder/Decoder Online | 100% Private | ToolsAtZero",
    shortName: "Base64",
    description: "Encode binary or text files into Base64 format and decode them back.",
    tagline: "Encode or decode Base64 data",
    keywords: ["base64 encoder", "base64 decoder", "encode text", "decode binary", "client-side"],
    icon: Binary,
    href: "/tools/base64-encoder-decoder",
    isReady: true,
    category: "developer",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    targetSeoString: "Free JWT Decoder Online | 100% Private | ToolsAtZero",
    shortName: "JWT Decoder",
    description: "Inspect JSON Web Tokens (JWT) payload, headers, and signatures locally.",
    tagline: "Decode and inspect JWT auth tokens",
    keywords: ["jwt", "jwt decoder", "token decode", "json web token", "client-side"],
    icon: KeyRound,
    href: "/tools/jwt-decoder",
    isReady: true,
    category: "developer",
  },
  {
    slug: "text-diff-checker",
    name: "Text Diff Checker",
    targetSeoString: "Free Text Diff Checker Online | 100% Private | ToolsAtZero",
    shortName: "Diff Checker",
    description: "Compare text blocks side-by-side to highlight line-by-line differences.",
    tagline: "Compare text differences visually",
    keywords: ["text diff", "diff checker", "compare text", "difference checker", "client-side"],
    icon: GitCompareArrows,
    href: "/tools/text-diff-checker",
    isReady: true,
    category: "developer",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    targetSeoString: "Free Hash Generator Online | 100% Private | ToolsAtZero",
    shortName: "Hash Gen",
    description: "Compute MD5, SHA-1, SHA-256, and SHA-512 hashes in your browser.",
    tagline: "Generate cryptographic checksum hashes",
    keywords: ["hash generator", "md5 generator", "sha256 hash", "checksum builder", "client-side"],
    icon: Hash,
    href: "/tools/hash-generator",
    isReady: true,
    category: "developer",
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    targetSeoString: "Free SQL Formatter Online | 100% Private | ToolsAtZero",
    shortName: "SQL Formatter",
    description: "Beautify and indent SQL queries with custom indentation levels.",
    tagline: "Beautify and indent SQL query scripts",
    keywords: ["sql formatter", "format sql", "beautify sql", "sql indent", "client-side"],
    icon: Database,
    href: "/tools/sql-formatter",
    isReady: true,
    category: "developer",
  },
  {
    slug: "xml-to-json",
    name: "XML to JSON",
    targetSeoString: "Free XML to JSON Online | 100% Private | ToolsAtZero",
    shortName: "XML to JSON",
    description: "Convert XML data structures into clean JSON objects in memory.",
    tagline: "Convert XML documents to JSON structure",
    keywords: ["xml to json", "xml converter", "parse xml", "xml2json", "client-side"],
    icon: Code,
    href: "/tools/xml-to-json",
    isReady: true,
    category: "developer",
  },
  {
    slug: "regex-tester",
    name: "RegEx Tester",
    targetSeoString: "Free RegEx Tester Online | 100% Private | ToolsAtZero",
    shortName: "RegEx Tester",
    description: "Test regular expressions with syntax highlights and match breakdowns.",
    tagline: "Test regular expression match groups",
    keywords: ["regex tester", "regexp test", "javascript regex", "regex explainer", "client-side"],
    icon: Search,
    href: "/tools/regex-tester",
    isReady: true,
    category: "developer",
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    targetSeoString: "Free HTML Entity Encoder Online | 100% Private | ToolsAtZero",
    shortName: "HTML Entities",
    description: "Encode special characters to HTML entities and decode them back.",
    tagline: "Encode or decode HTML entities",
    keywords: ["html entities", "entity encoder", "html escape", "unescape html", "client-side"],
    icon: FileCode,
    href: "/tools/html-entities",
    isReady: true,
    category: "developer",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    targetSeoString: "Free UUID Generator Online | 100% Private | ToolsAtZero",
    shortName: "UUID Gen",
    description: "Bulk generate cryptographically secure UUID v4 tokens locally.",
    tagline: "Generate secure UUID/GUID v4 strings",
    keywords: ["uuid generator", "guid generator", "random uuid", "uuid v4", "client-side"],
    icon: Fingerprint,
    href: "/tools/uuid-generator",
    isReady: true,
    category: "developer",
  },

  // ── 3. OFFICE & TEXT TOOLS (8 Tools) ──
  {
    slug: "case-converter",
    name: "Advanced Case Converter",
    targetSeoString: "Free Advanced Case Converter Online | 100% Private | ToolsAtZero",
    shortName: "Case Converter",
    description: "Convert text camelCase, snake_case, UPPERCASE, and sentence structures.",
    tagline: "Change text cases and naming formats",
    keywords: ["case converter", "text converter", "snake case", "camelcase", "client-side"],
    icon: CaseSensitive,
    href: "/tools/case-converter",
    isReady: true,
    category: "office",
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    targetSeoString: "Free CSV to JSON Online | 100% Private | ToolsAtZero",
    shortName: "CSV to JSON",
    description: "Format table CSV spreadsheets into clean JSON array collections.",
    tagline: "Format spreadsheet CSV tables to JSON",
    keywords: ["csv to json", "convert csv", "parse csv", "table data", "client-side"],
    icon: FileSpreadsheet,
    href: "/tools/csv-to-json",
    isReady: true,
    category: "office",
  },
  {
    slug: "csv-to-excel",
    name: "CSV to Excel",
    targetSeoString: "Free CSV to Excel Online | 100% Private | ToolsAtZero",
    shortName: "CSV to Excel",
    description: "Convert comma-separated tables into Microsoft Excel spreadsheet (.xls) files.",
    tagline: "Convert CSV data to Excel spreadsheet tables",
    keywords: ["csv to excel", "csv to xls", "spreadsheet builder", "table converter", "client-side"],
    icon: FileSpreadsheet,
    href: "/tools/csv-to-excel",
    isReady: true,
    category: "office",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    targetSeoString: "Free Word Counter Online | 100% Private | ToolsAtZero",
    shortName: "Word Counter",
    description: "Analyze word counts, reading speeds, sentence stats, and density scores.",
    tagline: "Analyze text statistics and density",
    keywords: ["word counter", "character counter", "text length", "word metrics", "client-side"],
    icon: LetterText,
    href: "/tools/word-counter",
    isReady: true,
    category: "office",
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    targetSeoString: "Free Find & Replace Online | 100% Private | ToolsAtZero",
    shortName: "Find & Replace",
    description: "Search text streams using string search or regex and replace matches.",
    tagline: "Search and replace text strings",
    keywords: ["find replace", "replace text", "find string", "regex replace", "client-side"],
    icon: ChevronsUpDown,
    href: "/tools/find-replace",
    isReady: true,
    category: "office",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    targetSeoString: "Free Lorem Ipsum Generator Online | 100% Private | ToolsAtZero",
    shortName: "Lorem Ipsum",
    description: "Generate mockup paragraphs, headings, and placeholder text loops.",
    tagline: "Generate layout placeholder dummy text",
    keywords: ["lorem ipsum", "dummy text", "placeholder generator", "layout text", "client-side"],
    icon: FileCode2,
    href: "/tools/lorem-ipsum",
    isReady: true,
    category: "office",
  },
  {
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    targetSeoString: "Free Remove Duplicate Lines Online | 100% Private | ToolsAtZero",
    shortName: "Remove Duplicates",
    description: "Filter duplicate lines out of list arrays in browser memory frames.",
    tagline: "Filter duplicate lines from lists",
    keywords: ["remove duplicate lines", "deduplicate list", "unique lines", "clean text", "client-side"],
    icon: AlignLeft,
    href: "/tools/remove-duplicate-lines",
    isReady: true,
    category: "office",
  },
  {
    slug: "sort-text-lines",
    name: "Sort Text Lines",
    targetSeoString: "Free Sort Text Lines Online | 100% Private | ToolsAtZero",
    shortName: "Sort Lines",
    description: "Sort lines alphabetically, numerically, reversely, or by length.",
    tagline: "Sort text lists and lines sequentially",
    keywords: ["sort lines", "sort text", "alphabetical sort", "reorder lines", "client-side"],
    icon: ListOrdered,
    href: "/tools/sort-text-lines",
    isReady: true,
    category: "office",
  },

  // ── 4. IMAGE TOOLS (8 Tools) ──
  {
    slug: "image-compressor",
    name: "Image Compressor",
    targetSeoString: "Free Image Compressor Online | 100% Private | ToolsAtZero",
    shortName: "Compress Image",
    description: "Compress JPEG, PNG, and WebP files client-side inside canvas frames.",
    tagline: "Compress images with zero quality loss",
    keywords: ["compress image", "shrink photo", "reduce size", "optimize jpg", "client-side"],
    icon: FileImage,
    href: "/tools/image-compressor",
    isReady: true,
    category: "image",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    targetSeoString: "Free Image Resizer Online | 100% Private | ToolsAtZero",
    shortName: "Resize Image",
    description: "Adjust image heights and widths using local canvas scaling parameters.",
    tagline: "Change canvas height and width dimensions",
    keywords: ["resize image", "scale photo", "change dimensions", "width scaler", "client-side"],
    icon: Maximize2,
    href: "/tools/image-resizer",
    isReady: true,
    category: "image",
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    targetSeoString: "Free PNG to JPG Online | 100% Private | ToolsAtZero",
    shortName: "PNG to JPG",
    description: "Convert PNG images to JPEG format with custom quality sliders.",
    tagline: "Convert PNG files to JPG format",
    keywords: ["png to jpg", "convert png", "jpeg", "image format", "client-side"],
    icon: Image,
    href: "/tools/png-to-jpg",
    isReady: true,
    category: "image",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    targetSeoString: "Free JPG to PNG Online | 100% Private | ToolsAtZero",
    shortName: "JPG to PNG",
    description: "Convert JPEG files to PNG transparent image structures.",
    tagline: "Convert JPG files to PNG format",
    keywords: ["jpg to png", "jpeg to png", "convert jpg", "transparent png", "client-side"],
    icon: Image,
    href: "/tools/jpg-to-png",
    isReady: true,
    category: "image",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    targetSeoString: "Free Image Cropper Online | 100% Private | ToolsAtZero",
    shortName: "Crop Image",
    description: "Crop local photos and adjust boundary coordinate grids.",
    tagline: "Crop and adjust image coordinates",
    keywords: ["crop image", "cut photo", "cropping", "dimensions crop", "client-side"],
    icon: Crop,
    href: "/tools/image-cropper",
    isReady: true,
    category: "image",
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    targetSeoString: "Free Color Picker Online | 100% Private | ToolsAtZero",
    shortName: "Color Picker",
    description: "Extract color hex, rgb, and hsl codes from loaded image pixels.",
    tagline: "Extract colors from image pixel array",
    keywords: ["color picker", "hex color", "extract colors", "eyedropper", "client-side"],
    icon: Pipette,
    href: "/tools/color-picker",
    isReady: true,
    category: "image",
  },
  {
    slug: "base64-to-image",
    name: "Base64 to Image",
    targetSeoString: "Free Base64 to Image Online | 100% Private | ToolsAtZero",
    shortName: "Base64 to Image",
    description: "Render Base64 strings into visual images and download them.",
    tagline: "Render Base64 strings to images",
    keywords: ["base64 to image", "data uri", "decode base64", "base64 image", "client-side"],
    icon: RefreshCw,
    href: "/tools/base64-to-image",
    isReady: true,
    category: "image",
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG",
    targetSeoString: "Free SVG to PNG Online | 100% Private | ToolsAtZero",
    shortName: "SVG to PNG",
    description: "Rasterize vector SVG files into standard transparent PNG formats.",
    tagline: "Convert SVG vector strings to PNG format",
    keywords: ["svg to png", "vector to raster", "convert svg", "svg2png", "client-side"],
    icon: Sliders,
    href: "/tools/svg-to-png",
    isReady: true,
    category: "image",
  },

  // ── 5. WEB TOOLS (6 Tools) ──
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder/Decoder",
    targetSeoString: "Free URL Encoder/Decoder Online | 100% Private | ToolsAtZero",
    shortName: "URL Encoder",
    description: "Encode or decode URL parameters with percent encoding.",
    tagline: "Encode or decode URL components",
    keywords: ["url encode", "url decode", "percent encoding", "uri encoder", "client-side"],
    icon: Link2,
    href: "/tools/url-encoder-decoder",
    isReady: true,
    category: "web",
  },
  {
    slug: "html-minifier",
    name: "HTML Minifier",
    targetSeoString: "Free HTML Minifier Online | 100% Private | ToolsAtZero",
    shortName: "HTML Minify",
    description: "Minify HTML pages by stripping whitespace characters and comments.",
    tagline: "Compress and minify HTML structures",
    keywords: ["html minifier", "minify html", "compress html", "page size minifier", "client-side"],
    icon: Trash2,
    href: "/tools/html-minifier",
    isReady: true,
    category: "web",
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    targetSeoString: "Free CSS Minifier Online | 100% Private | ToolsAtZero",
    shortName: "CSS Minify",
    description: "Compress CSS stylesheets by removing spacing rules and comments.",
    tagline: "Compress and minify CSS styles",
    keywords: ["css minifier", "minify css", "compress css", "clean stylesheets", "client-side"],
    icon: Trash2,
    href: "/tools/css-minifier",
    isReady: true,
    category: "web",
  },
  {
    slug: "javascript-minifier",
    name: "JS Minifier",
    targetSeoString: "Free JS Minifier Online | 100% Private | ToolsAtZero",
    shortName: "JS Minifier",
    description: "Minify and compact JS script code structures locally.",
    tagline: "Compact and minify JS source code",
    keywords: ["js minifier", "minify javascript", "js compressor", "obfuscate js", "client-side"],
    icon: Trash2,
    href: "/tools/javascript-minifier",
    isReady: true,
    category: "web",
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    targetSeoString: "Free Meta Tag Generator Online | 100% Private | ToolsAtZero",
    shortName: "Meta Gen",
    description: "Generate SEO-optimized HTML header meta tag blocks.",
    tagline: "Generate HTML header SEO meta tags",
    keywords: ["meta tag generator", "seo meta", "og tags", "twitter cards", "client-side"],
    icon: Tags,
    href: "/tools/meta-tag-generator",
    isReady: true,
    category: "web",
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    targetSeoString: "Free Robots.txt Generator Online | 100% Private | ToolsAtZero",
    shortName: "Robots Gen",
    description: "Create search engine crawler instruction sitemaps.",
    tagline: "Generate custom Robots.txt rules text",
    keywords: ["robots txt", "robots.txt generator", "crawler rules", "sitemap index", "client-side"],
    icon: Bot,
    href: "/tools/robots-txt-generator",
    isReady: true,
    category: "web",
  },

  // ── 6. TIME TOOLS (4 Tools) ──
  {
    slug: "epoch-converter",
    name: "Epoch Converter",
    targetSeoString: "Free Epoch Converter Online | 100% Private | ToolsAtZero",
    shortName: "Epoch",
    description: "Convert Unix timestamps to local and UTC date formatting.",
    tagline: "Convert Unix epoch timestamps to dates",
    keywords: ["epoch converter", "unix timestamp", "epoch time", "milliseconds convert", "client-side"],
    icon: Calendar,
    href: "/tools/epoch-converter",
    isReady: true,
    category: "time",
  },
  {
    slug: "time-zone-converter",
    name: "Time Zone Converter",
    targetSeoString: "Free Time Zone Converter Online | 100% Private | ToolsAtZero",
    shortName: "Timezones",
    description: "Convert date times across multiple regional global zones.",
    tagline: "Compare and convert global timezones",
    keywords: ["timezone converter", "convert time zone", "gmt utc est", "teams timezone", "client-side"],
    icon: Globe,
    href: "/tools/time-zone-converter",
    isReady: true,
    category: "time",
  },
  {
    slug: "date-difference",
    name: "Date Difference Calculator",
    targetSeoString: "Free Date Difference Calculator Online | 100% Private | ToolsAtZero",
    shortName: "Date Difference",
    description: "Compute the number of years, months, and days between target dates.",
    tagline: "Calculate days elapsed between date inputs",
    keywords: ["date difference", "days between dates", "date calculator", "years difference", "client-side"],
    icon: CalendarDays,
    href: "/tools/date-difference",
    isReady: true,
    category: "time",
  },
  {
    slug: "time-calculator",
    name: "Add/Subtract Time",
    targetSeoString: "Free Add/Subtract Time Online | 100% Private | ToolsAtZero",
    shortName: "Time Calc",
    description: "Add or subtract duration offsets from a starting date.",
    tagline: "Perform duration arithmetic on dates",
    keywords: ["add time to date", "time calculator", "subtract time", "date offsets", "client-side"],
    icon: CalendarPlus,
    href: "/tools/time-calculator",
    isReady: true,
    category: "time",
  },

  {
    slug: "ai-background-remover",
    name: "AI Background Remover",
    targetSeoString: "Free AI Background Remover - 100% Local | ToolsAtZero",
    shortName: "Background Remover",
    description: "Remove image backgrounds instantly in your browser.",
    tagline: "Remove image backgrounds locally using browser power",
    keywords: ["free ai background remover", "local background remover", "privacy first", "client-side", "offline"],
    icon: Crop,
    href: "/tools/ai-background-remover",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-image-upscaler",
    name: "AI Image Upscaler",
    targetSeoString: "Free AI Image Upscaler - 100% Local | ToolsAtZero",
    shortName: "Image Upscaler",
    description: "Upscale and enhance image resolution client-side.",
    tagline: "Upscale and enhance images locally by 2x or 4x",
    keywords: ["free ai image upscaler", "local image upscaler", "privacy first", "client-side", "offline"],
    icon: Maximize2,
    href: "/tools/ai-image-upscaler",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-image-denoiser",
    name: "AI Image Denoiser",
    targetSeoString: "Free AI Image Denoiser - 100% Local | ToolsAtZero",
    shortName: "Image Denoiser",
    description: "Remove digital noise and grain from photos locally.",
    tagline: "Reduce noise and grain from photos in-browser",
    keywords: ["free ai image denoiser", "local image denoiser", "privacy first", "client-side", "offline"],
    icon: Sliders,
    href: "/tools/ai-image-denoiser",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-face-blur",
    name: "AI Face Blur",
    targetSeoString: "Free AI Face Blur - 100% Local | ToolsAtZero",
    shortName: "Face Blur",
    description: "Detect and blur faces in photos client-side for privacy.",
    tagline: "Blur faces automatically inside your browser",
    keywords: ["free ai face blur", "local face blur", "privacy first", "client-side", "offline"],
    icon: EyeOff,
    href: "/tools/ai-face-blur",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-object-blur",
    name: "AI Object Blur",
    targetSeoString: "Free AI Object Blur - 100% Local | ToolsAtZero",
    shortName: "Object Blur",
    description: "Blur custom selected objects in images locally.",
    tagline: "Select and blur custom image segments in-memory",
    keywords: ["free ai object blur", "local object blur", "privacy first", "client-side", "offline"],
    icon: EyeOff,
    href: "/tools/ai-object-blur",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-image-sharpener",
    name: "AI Image Sharpener",
    targetSeoString: "Free AI Image Sharpener - 100% Local | ToolsAtZero",
    shortName: "Image Sharpener",
    description: "Sharpen blurry photos and enhance details client-side.",
    tagline: "Sharpen and clarify blurry images in-browser",
    keywords: ["free ai image sharpener", "local image sharpener", "privacy first", "client-side", "offline"],
    icon: Sun,
    href: "/tools/ai-image-sharpener",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-colorize-photo",
    name: "AI Colorize Photo",
    targetSeoString: "Free AI Colorize Photo - 100% Local | ToolsAtZero",
    shortName: "Colorize Photo",
    description: "Colorize black and white photos locally in your browser.",
    tagline: "Colorize black and white images in-browser",
    keywords: ["free ai colorize photo", "local colorize photo", "privacy first", "client-side", "offline"],
    icon: Pipette,
    href: "/tools/ai-colorize-photo",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-cartoon-generator",
    name: "AI Cartoon Generator",
    targetSeoString: "Free AI Cartoon Generator - 100% Local | ToolsAtZero",
    shortName: "Cartoon Generator",
    description: "Convert photos into stylized cartoon artwork client-side.",
    tagline: "Stylize photos into custom cartoon art in-browser",
    keywords: ["free ai cartoon generator", "local cartoon generator", "privacy first", "client-side", "offline"],
    icon: Sparkles,
    href: "/tools/ai-cartoon-generator",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-pencil-sketch",
    name: "AI Pencil Sketch Converter",
    targetSeoString: "Free AI Pencil Sketch Converter - 100% Local | ToolsAtZero",
    shortName: "Pencil Sketch Converter",
    description: "Convert images to realistic pencil drawings client-side.",
    tagline: "Convert images to sketch formats in-memory",
    keywords: ["free ai pencil sketch converter", "local pencil sketch converter", "privacy first", "client-side", "offline"],
    icon: FileImage,
    href: "/tools/ai-pencil-sketch",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-portrait-enhancer",
    name: "AI Portrait Enhancer",
    targetSeoString: "Free AI Portrait Enhancer - 100% Local | ToolsAtZero",
    shortName: "Portrait Enhancer",
    description: "Enhance faces and lighting in portrait photos locally.",
    tagline: "Enhance faces and portrait lighting client-side",
    keywords: ["free ai portrait enhancer", "local portrait enhancer", "privacy first", "client-side", "offline"],
    icon: Sliders,
    href: "/tools/ai-portrait-enhancer",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-remove-jpeg-artifacts",
    name: "AI Remove JPEG Artifacts",
    targetSeoString: "Free AI Remove JPEG Artifacts - 100% Local | ToolsAtZero",
    shortName: "Remove JPEG Artifacts",
    description: "Smooth and restore pixelated JPEG compression artifacts.",
    tagline: "Clean blocky compression artifacts from JPEG images",
    keywords: ["free ai remove jpeg artifacts", "local remove jpeg artifacts", "privacy first", "client-side", "offline"],
    icon: RefreshCw,
    href: "/tools/ai-remove-jpeg-artifacts",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-auto-crop",
    name: "AI Auto Crop",
    targetSeoString: "Free AI Auto Crop - 100% Local | ToolsAtZero",
    shortName: "Auto Crop",
    description: "Smart crop images to focus on subject layers client-side.",
    tagline: "Smart crop photos client-side to center subjects",
    keywords: ["free ai auto crop", "local auto crop", "privacy first", "client-side", "offline"],
    icon: Crop,
    href: "/tools/ai-auto-crop",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-image-caption",
    name: "AI Image Caption Generator",
    targetSeoString: "Free AI Image Caption Generator - 100% Local | ToolsAtZero",
    shortName: "Image Caption Generator",
    description: "Generate descriptive captions for images using client-side AI.",
    tagline: "Generate text descriptions for photos locally",
    keywords: ["free ai image caption generator", "local image caption generator", "privacy first", "client-side", "offline"],
    icon: Brain,
    href: "/tools/ai-image-caption",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-dominant-color",
    name: "AI Dominant Color Extractor",
    targetSeoString: "Free AI Dominant Color Extractor - 100% Local | ToolsAtZero",
    shortName: "Dominant Color Extractor",
    description: "Extract color palettes and hex codes from photos locally.",
    tagline: "Extract dominant color palettes from images",
    keywords: ["free ai dominant color extractor", "local dominant color extractor", "privacy first", "client-side", "offline"],
    icon: Pipette,
    href: "/tools/ai-dominant-color",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-duplicate-detector",
    name: "AI Duplicate Image Detector",
    targetSeoString: "Free AI Duplicate Image Detector - 100% Local | ToolsAtZero",
    shortName: "Duplicate Image Detector",
    description: "Compare image hash layers to detect duplicates locally.",
    tagline: "Compare image hashes to locate duplicate files",
    keywords: ["free ai duplicate image detector", "local duplicate image detector", "privacy first", "client-side", "offline"],
    icon: GitCompareArrows,
    href: "/tools/ai-duplicate-detector",
    isReady: false,
    category: "image",
  },
  {
    slug: "ai-ocr",
    name: "AI OCR",
    targetSeoString: "Free AI OCR - 100% Local | ToolsAtZero",
    shortName: "OCR",
    description: "Extract text characters from scanned image layers locally.",
    tagline: "Extract text from images locally in-browser",
    keywords: ["free ai ocr", "local ocr", "privacy first", "client-side", "offline"],
    icon: FileText,
    href: "/tools/ai-ocr",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-handwriting-to-text",
    name: "AI Handwriting to Text",
    targetSeoString: "Free AI Handwriting to Text - 100% Local | ToolsAtZero",
    shortName: "Handwriting to Text",
    description: "Transcribe handwritten note scans into plain text formats.",
    tagline: "Convert handwritten notes to text in-browser",
    keywords: ["free ai handwriting to text", "local handwriting to text", "privacy first", "client-side", "offline"],
    icon: LetterText,
    href: "/tools/ai-handwriting-to-text",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-receipt-scanner",
    name: "AI Receipt Scanner",
    targetSeoString: "Free AI Receipt Scanner - 100% Local | ToolsAtZero",
    shortName: "Receipt Scanner",
    description: "Extract pricing, store details, and tax totals from receipts.",
    tagline: "Scan receipt details and extract transaction fields",
    keywords: ["free ai receipt scanner", "local receipt scanner", "privacy first", "client-side", "offline"],
    icon: FileSpreadsheet,
    href: "/tools/ai-receipt-scanner",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-invoice-reader",
    name: "AI Invoice Reader",
    targetSeoString: "Free AI Invoice Reader - 100% Local | ToolsAtZero",
    shortName: "Invoice Reader",
    description: "Extract invoice details, payment fields, and tables locally.",
    tagline: "Scan invoice files and extract billing datasets",
    keywords: ["free ai invoice reader", "local invoice reader", "privacy first", "client-side", "offline"],
    icon: FileText,
    href: "/tools/ai-invoice-reader",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-business-card-scanner",
    name: "AI Business Card Scanner",
    targetSeoString: "Free AI Business Card Scanner - 100% Local | ToolsAtZero",
    shortName: "Business Card Scanner",
    description: "Extract contacts, email tags, and links from business cards.",
    tagline: "Extract contact info from business cards locally",
    keywords: ["free ai business card scanner", "local business card scanner", "privacy first", "client-side", "offline"],
    icon: LetterText,
    href: "/tools/ai-business-card-scanner",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-table-extractor",
    name: "AI Table Extractor",
    targetSeoString: "Free AI Table Extractor - 100% Local | ToolsAtZero",
    shortName: "Table Extractor",
    description: "Extract grid data structures from document image layers.",
    tagline: "Convert image grids to CSV spreadsheet tables",
    keywords: ["free ai table extractor", "local table extractor", "privacy first", "client-side", "offline"],
    icon: FileSpreadsheet,
    href: "/tools/ai-table-extractor",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-pdf-summarizer",
    name: "AI PDF Summarizer",
    targetSeoString: "Free AI PDF Summarizer - 100% Local | ToolsAtZero",
    shortName: "PDF Summarizer",
    description: "Extract text and summarize PDF documents 100% client-side.",
    tagline: "Summarize PDF documents locally using browser memory",
    keywords: ["free ai pdf summarizer", "local pdf summarizer", "privacy first", "client-side", "offline"],
    icon: Files,
    href: "/tools/ai-pdf-summarizer",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-keyword-extractor",
    name: "AI Keyword Extractor",
    targetSeoString: "Free AI Keyword Extractor - 100% Local | ToolsAtZero",
    shortName: "Keyword Extractor",
    description: "Extract high-density SEO keywords from documents locally.",
    tagline: "Locate high-frequency keyword terms in text",
    keywords: ["free ai keyword extractor", "local keyword extractor", "privacy first", "client-side", "offline"],
    icon: Tags,
    href: "/tools/ai-keyword-extractor",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-document-language-detector",
    name: "AI Document Language Detector",
    targetSeoString: "Free AI Document Language Detector - 100% Local | ToolsAtZero",
    shortName: "Document Language Detector",
    description: "Detect the language of text blocks and documents locally.",
    tagline: "Analyze text syntax to determine document language",
    keywords: ["free ai document language detector", "local document language detector", "privacy first", "client-side", "offline"],
    icon: Globe,
    href: "/tools/ai-document-language-detector",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-readability-analyzer",
    name: "AI Readability Analyzer",
    targetSeoString: "Free AI Readability Analyzer - 100% Local | ToolsAtZero",
    shortName: "Readability Analyzer",
    description: "Analyze Flesch-Kincaid readability scoring levels locally.",
    tagline: "Evaluate reading level scores on text contents",
    keywords: ["free ai readability analyzer", "local readability analyzer", "privacy first", "client-side", "offline"],
    icon: LetterText,
    href: "/tools/ai-readability-analyzer",
    isReady: false,
    category: "pdf",
  },
  {
    slug: "ai-grammar-checker",
    name: "AI Grammar Checker",
    targetSeoString: "Free AI Grammar Checker - 100% Local | ToolsAtZero",
    shortName: "Grammar Checker",
    description: "Check and repair syntax and grammar layout errors locally.",
    tagline: "Correct syntax and write better content offline",
    keywords: ["free ai grammar checker", "local grammar checker", "privacy first", "client-side", "offline"],
    icon: LetterText,
    href: "/tools/ai-grammar-checker",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-spell-checker",
    name: "AI Spell Checker",
    targetSeoString: "Free AI Spell Checker - 100% Local | ToolsAtZero",
    shortName: "Spell Checker",
    description: "Detect spelling slips and recommend local corrections.",
    tagline: "Identify spelling issues and fix text mistakes",
    keywords: ["free ai spell checker", "local spell checker", "privacy first", "client-side", "offline"],
    icon: LetterText,
    href: "/tools/ai-spell-checker",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-tone-detector",
    name: "AI Tone Detector",
    targetSeoString: "Free AI Tone Detector - 100% Local | ToolsAtZero",
    shortName: "Tone Detector",
    description: "Analyze text structures to identify emotional tone layouts.",
    tagline: "Detect sentiment and tone metrics in writing",
    keywords: ["free ai tone detector", "local tone detector", "privacy first", "client-side", "offline"],
    icon: Sliders,
    href: "/tools/ai-tone-detector",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-tone-rewriter",
    name: "AI Tone Rewriter",
    targetSeoString: "Free AI Tone Rewriter - 100% Local | ToolsAtZero",
    shortName: "Tone Rewriter",
    description: "Rewrite text structures to adjust voice styles locally.",
    tagline: "Rewrite text into formal, casual, or custom tones",
    keywords: ["free ai tone rewriter", "local tone rewriter", "privacy first", "client-side", "offline"],
    icon: RefreshCw,
    href: "/tools/ai-tone-rewriter",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-sentence-simplifier",
    name: "AI Sentence Simplifier",
    targetSeoString: "Free AI Sentence Simplifier - 100% Local | ToolsAtZero",
    shortName: "Sentence Simplifier",
    description: "Simplify complex paragraphs into readable sentences.",
    tagline: "Shorten and simplify complex reading blocks",
    keywords: ["free ai sentence simplifier", "local sentence simplifier", "privacy first", "client-side", "offline"],
    icon: Scissors,
    href: "/tools/ai-sentence-simplifier",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-paraphraser",
    name: "AI Paraphraser",
    targetSeoString: "Free AI Paraphraser - 100% Local | ToolsAtZero",
    shortName: "Paraphraser",
    description: "Rephrase paragraphs to build original expressions locally.",
    tagline: "Rephrase text blocks without losing core intent",
    keywords: ["free ai paraphraser", "local paraphraser", "privacy first", "client-side", "offline"],
    icon: RefreshCw,
    href: "/tools/ai-paraphraser",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-text-summarizer",
    name: "AI Text Summarizer",
    targetSeoString: "Free AI Text Summarizer - 100% Local | ToolsAtZero",
    shortName: "Text Summarizer",
    description: "Compress long text blocks into bulleted layouts.",
    tagline: "Compress writing structures into brief summaries",
    keywords: ["free ai text summarizer", "local text summarizer", "privacy first", "client-side", "offline"],
    icon: Scissors,
    href: "/tools/ai-text-summarizer",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-title-generator",
    name: "AI Title Generator",
    targetSeoString: "Free AI Title Generator - 100% Local | ToolsAtZero",
    shortName: "Title Generator",
    description: "Generate SEO headings and blog titles from text inputs.",
    tagline: "Create engaging SEO article title layouts",
    keywords: ["free ai title generator", "local title generator", "privacy first", "client-side", "offline"],
    icon: Tags,
    href: "/tools/ai-title-generator",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-emoji-suggestion",
    name: "AI Emoji Suggestion Tool",
    targetSeoString: "Free AI Emoji Suggestion Tool - 100% Local | ToolsAtZero",
    shortName: "Emoji Suggestion Tool",
    description: "Suggest contextually related emojis for social text copy.",
    tagline: "Insert matching emojis dynamically based on context",
    keywords: ["free ai emoji suggestion tool", "local emoji suggestion tool", "privacy first", "client-side", "offline"],
    icon: Sparkles,
    href: "/tools/ai-emoji-suggestion",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-language-detector",
    name: "AI Language Detector",
    targetSeoString: "Free AI Language Detector - 100% Local | ToolsAtZero",
    shortName: "Language Detector",
    description: "Detect the language of copy blocks locally in real-time.",
    tagline: "Identify text language using local classification",
    keywords: ["free ai language detector", "local language detector", "privacy first", "client-side", "offline"],
    icon: Globe,
    href: "/tools/ai-language-detector",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-speech-to-text",
    name: "AI Speech to Text",
    targetSeoString: "Free AI Speech to Text - 100% Local | ToolsAtZero",
    shortName: "Speech to Text",
    description: "Transcribe voice streams into plain text formats locally.",
    tagline: "Transcribe recording sessions completely offline",
    keywords: ["free ai speech to text", "local speech to text", "privacy first", "client-side", "offline"],
    icon: Volume2,
    href: "/tools/ai-speech-to-text",
    isReady: false,
    category: "web",
  },
  {
    slug: "ai-voice-activity-detector",
    name: "AI Voice Activity Detector",
    targetSeoString: "Free AI Voice Activity Detector - 100% Local | ToolsAtZero",
    shortName: "Voice Activity Detector",
    description: "Identify speech segments in audio timelines client-side.",
    tagline: "Analyze audio files to isolate speech segments",
    keywords: ["free ai voice activity detector", "local voice activity detector", "privacy first", "client-side", "offline"],
    icon: Sliders,
    href: "/tools/ai-voice-activity-detector",
    isReady: false,
    category: "web",
  },
  {
    slug: "ai-silence-remover",
    name: "AI Silence Remover",
    targetSeoString: "Free AI Silence Remover - 100% Local | ToolsAtZero",
    shortName: "Silence Remover",
    description: "Trim silences and quiet frames from audio file streams.",
    tagline: "Auto-strip silences from recorded audio tracks",
    keywords: ["free ai silence remover", "local silence remover", "privacy first", "client-side", "offline"],
    icon: Scissors,
    href: "/tools/ai-silence-remover",
    isReady: false,
    category: "web",
  },
  {
    slug: "ai-audio-language-detector",
    name: "AI Audio Language Detector",
    targetSeoString: "Free AI Audio Language Detector - 100% Local | ToolsAtZero",
    shortName: "Audio Language Detector",
    description: "Identify the language spoken in an audio file locally.",
    tagline: "Detect spoken languages in audio recordings",
    keywords: ["free ai audio language detector", "local audio language detector", "privacy first", "client-side", "offline"],
    icon: Globe,
    href: "/tools/ai-audio-language-detector",
    isReady: false,
    category: "web",
  },
  {
    slug: "ai-noise-reduction",
    name: "AI Noise Reduction",
    targetSeoString: "Free AI Noise Reduction - 100% Local | ToolsAtZero",
    shortName: "Noise Reduction",
    description: "Clean ambient hums and background noises from audio files.",
    tagline: "Apply local audio filters to denoise voice tracks",
    keywords: ["free ai noise reduction", "local noise reduction", "privacy first", "client-side", "offline"],
    icon: Sliders,
    href: "/tools/ai-noise-reduction",
    isReady: false,
    category: "web",
  },
  {
    slug: "ai-code-language-detector",
    name: "AI Code Language Detector",
    targetSeoString: "Free AI Code Language Detector - 100% Local | ToolsAtZero",
    shortName: "Code Language Detector",
    description: "Analyze code structures to identify programming languages.",
    tagline: "Detect code languages using local file syntaxes",
    keywords: ["free ai code language detector", "local code language detector", "privacy first", "client-side", "offline"],
    icon: Code,
    href: "/tools/ai-code-language-detector",
    isReady: false,
    category: "developer",
  },
  {
    slug: "ai-regex-explainer",
    name: "AI Regex Explainer",
    targetSeoString: "Free AI Regex Explainer - 100% Local | ToolsAtZero",
    shortName: "Regex Explainer",
    description: "Analyze and explain regular expression rules locally.",
    tagline: "Break down regular expressions with simple steps",
    keywords: ["free ai regex explainer", "local regex explainer", "privacy first", "client-side", "offline"],
    icon: FileCode,
    href: "/tools/ai-regex-explainer",
    isReady: false,
    category: "developer",
  },
  {
    slug: "ai-json-error-explainer",
    name: "AI JSON Error Explainer",
    targetSeoString: "Free AI JSON Error Explainer - 100% Local | ToolsAtZero",
    shortName: "JSON Error Explainer",
    description: "Explain parsing errors and recommend JSON structures.",
    tagline: "Locate and correct broken JSON file parameters",
    keywords: ["free ai json error explainer", "local json error explainer", "privacy first", "client-side", "offline"],
    icon: Braces,
    href: "/tools/ai-json-error-explainer",
    isReady: false,
    category: "developer",
  },
  {
    slug: "ai-sql-formatter-explanation",
    name: "AI SQL Formatter with Explanation",
    targetSeoString: "Free AI SQL Formatter with Explanation - 100% Local | ToolsAtZero",
    shortName: "SQL Formatter with Explanation",
    description: "Format database queries and explain optimization rules.",
    tagline: "Format query inputs and review design suggestions",
    keywords: ["free ai sql formatter with explanation", "local sql formatter with explanation", "privacy first", "client-side", "offline"],
    icon: Database,
    href: "/tools/ai-sql-formatter-explanation",
    isReady: false,
    category: "developer",
  },
  {
    slug: "ai-commit-message-generator",
    name: "AI Commit Message Generator",
    targetSeoString: "Free AI Commit Message Generator - 100% Local | ToolsAtZero",
    shortName: "Commit Message Generator",
    description: "Generate conventional commit messages from git diffs.",
    tagline: "Draft clean conventional commit notes locally",
    keywords: ["free ai commit message generator", "local commit message generator", "privacy first", "client-side", "offline"],
    icon: GitCompareArrows,
    href: "/tools/ai-commit-message-generator",
    isReady: false,
    category: "developer",
  },
  {
    slug: "ai-resume-analyzer",
    name: "AI Resume Analyzer",
    targetSeoString: "Free AI Resume Analyzer - 100% Local | ToolsAtZero",
    shortName: "Resume Analyzer",
    description: "Analyze resume parameters for keyword score matches.",
    tagline: "Evaluate resume documents against job keyword indices",
    keywords: ["free ai resume analyzer", "local resume analyzer", "privacy first", "client-side", "offline"],
    icon: FileText,
    href: "/tools/ai-resume-analyzer",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-email-subject-analyzer",
    name: "AI Email Subject Analyzer",
    targetSeoString: "Free AI Email Subject Analyzer - 100% Local | ToolsAtZero",
    shortName: "Email Subject Analyzer",
    description: "Analyze open rate potentials for email subject headers.",
    tagline: "Evaluate email subject hooks for open rates",
    keywords: ["free ai email subject analyzer", "local email subject analyzer", "privacy first", "client-side", "offline"],
    icon: LetterText,
    href: "/tools/ai-email-subject-analyzer",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-password-strength-analyzer",
    name: "AI Password Strength Analyzer",
    targetSeoString: "Free AI Password Strength Analyzer - 100% Local | ToolsAtZero",
    shortName: "Password Strength Analyzer",
    description: "Evaluate password strength metrics locally with zero tracking.",
    tagline: "Assess password entropy levels securely in-browser",
    keywords: ["free ai password strength analyzer", "local password strength analyzer", "privacy first", "client-side", "offline"],
    icon: Fingerprint,
    href: "/tools/ai-password-strength-analyzer",
    isReady: false,
    category: "office",
  },
  {
    slug: "ai-qr-code-scanner",
    name: "AI QR Code Scanner",
    targetSeoString: "Free AI QR Code Scanner - 100% Local | ToolsAtZero",
    shortName: "QR Code Scanner",
    description: "Scan QR codes from images or webcam feeds client-side.",
    tagline: "Decode QR code assets securely in local browser memory",
    keywords: ["free ai qr code scanner", "local qr code scanner", "privacy first", "client-side", "offline"],
    icon: Camera,
    href: "/tools/ai-qr-code-scanner",
    isReady: false,
    category: "web",
  },
  {
    slug: "ai-barcode-scanner",
    name: "AI Barcode Scanner",
    targetSeoString: "Free AI Barcode Scanner - 100% Local | ToolsAtZero",
    shortName: "Barcode Scanner",
    description: "Scan barcodes from camera layers or image files locally.",
    tagline: "Decode UPC/EAN barcode lines inside your browser",
    keywords: ["free ai barcode scanner", "local barcode scanner", "privacy first", "client-side", "offline"],
    icon: Camera,
    href: "/tools/ai-barcode-scanner",
    isReady: false,
    category: "web",
  }
,

















];

import { calculatorList } from "@/modules/calculators/calculator.config";
import * as LucideIcons from "lucide-react";

const mappedCalculators: Tool[] = calculatorList.map((c) => {
  const IconComponent = (LucideIcons as any)[c.icon] || LucideIcons.Calculator;
  return {
    slug: c.slug,
    name: c.title,
    targetSeoString: `Free ${c.title} Online | 100% Private | ToolsAtZero`,
    shortName: c.shortTitle,
    description: c.description,
    tagline: c.description,
    keywords: c.keywords,
    icon: IconComponent,
    href: `/tools/${c.slug}`,
    isReady: true,
    category: "calculator" as const,
  };
});

export const tools: Tool[] = [...initialTools, ...mappedCalculators];

export const readyTools = tools.filter((t) => t.isReady);
export const comingSoonTools = tools.filter((t) => !t.isReady);

